.TH "bob" "1" "August 2009" "Sponge Web Framework" ""
.SH "NAME"
bob \- Utility script for the Sponge Web Framework
.SH "SYNOPSIS"
.B bob
.I <action>
.B [options]
.sp
.SH "DESCRIPTION"
This utility script provides commands speeding up your daily tasks on Sponge\-based projects maintenance.
.sp
Nowadays it just create and runs a project.
.sp
In next versions, will also run tests and setup deployment environment.
.sp
.SH "ACTIONS"
.TP
.BI "create <projectname>"
Creates a new project, which means creating a new folder in current directory, named
.B
projectname.
.TP
.B go
Start the cherrypy server using the configuration file settings.yml in current directory.
.SH "OPTIONS"
.TP
.I \-\-version
Show program's version number and exit.
.TP
.I \-h, \-\-help
Show this help message and exit.
.TP
.SH "SEE ALSO"
Check out the full documentation at /usr/share/doc/python-sponge/html
.SH "AUTHORS/CREDITS"
Developed by Gabriel Falcão.
.sp
.SH "LICENSE"
GNU/GPLv3. For the full license text refer to the LICENSE file in the
Sponge distribution.
